version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build: /home/oryadi/inception/srcs/requirements/mariadb/.
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception_net
    image: mariadb

  wordpress:
    container_name: wordpress
    build: /home/oryadi/inception/srcs/requirements/wordpress/.
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
    networks:
      - inception_net
    image: wordpress

  nginx:
    container_name: nginx
    build: /home/oryadi/inception/srcs/requirements/nginx/.
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/
    ports:
      - 443:443
    depends_on:
      - wordpress
    networks:
      - inception_net
    image: nginx

  static_website:
    image: static_website
    container_name: static_website
    build: /home/oryadi/inception/srcs/requirements/bonus/static/.
    restart: always
    ports:
      - 3000:3000

  ftp_server:
    container_name: ftp_server
    image: ftp_server
    build: /home/oryadi/inception/srcs/requirements/bonus/ftp-server/.
    volumes:
      - wordpress:/wordpress
    env_file:
      - .env
    restart: always
    ports:
      - 21:21
      - 40000-40010:40000-40010
  
  adminer:
    image: adminer
    container_name: adminer
    build: /home/oryadi/inception/srcs/requirements/bonus/adminer/.
    restart: always
    networks:
      - inception_net
    ports:
      - 8080:8080

  redis-cache:
    image: redis-cache
    container_name: redis-cache
    build: /home/oryadi/inception/srcs/requirements/bonus/redis-cache/.
    restart: always
    networks:
      - inception_net

  cadviser:
    image: cadviser
    container_name: cadviser
    build: /home/oryadi/inception/srcs/requirements/bonus/cadviser/.
    restart: always
    networks:
      - inception_net
    ports:
      - 8090:8090
    volumes:
      - /:/rootfs:ro \
      - /var/run:/var/run:ro \
      - /sys:/sys:ro \
      - /var/lib/docker/:/var/lib/docker:ro \
      - /dev/disk/:/dev/disk:ro \

networks:
  inception_net:
    name: inception_net

volumes:
  wordpress:
    driver : local
    driver_opts :
      o : bind
      device : /home/oryadi/data/wordpress/
      type: none

  mariadb:
    driver : local
    driver_opts :
      o : bind
      device : /home/oryadi/data/mariadb/
      type: none
    